### ISSUE TITLE
my speedtest-cli doesn't put out "Speed result"

### ISSUE THREAD

**Issue by pmwoodward3** [kitsunekyo/internet-speed-log#2]
Example json output:

{"upload": 394316287.9202392, "download": 710810930.4632795, "server": {"country": "United States", "url2": "http://sp2.aethosting.com/upload.php", "latency": xxx, "lon": "xxx", "sponsor": "AET Hosting Solutions", "name": "Washington, DC", "host": "speedtest.aethosting.com:8080", "d": 478.1985075127686, "lat": "38.9047", "url": "http://sp1.aethosting.com/upload.php", "cc": "US", "id": "7960"}, "timestamp": "2017-01-20T00:11:17.559249", "ping": 12.474}

**Comment by claym** [comment]
Nor does mine!

Running 

Ubuntu 16.10

the jq install here is: jq-1.5-1-a5b5cbe

**Comment by kitsunekyo** [comment]
what do you mean with 'doesnt put out'? the json output seems to work, is it the writing to a file that doesnt work?

if thats the case, make sure to have permission to write to the file and the file exists in the location you specified in the bash script

**Comment by onoj** [comment]
It seems i'm having the same issue - 
working through speedtest.sh, SPEED_RESULT has the correct JSON output, but TMP doesnt have any value at all, something seems to be going wrong with the jq command.

my log.json exists, and is writable and i'm using ubuntu 16.04. jq is version jq-1.5-1-a5b5cbe

**Comment by tobias-kuendig** [comment]
You'll have to initialize the json structure in the log file first. Otherwise the command won't work when running it against an empty file:

```bash
echo '{"log": []}' > log.json
```

**Comment by roycwc** [comment]
same here, seems like the jq parsing line has some problem. (on osx)

**Comment by kitsunekyo** [comment]
please let me know if clayms instructions could help you out.

**Comment by kitsunekyo** [comment]
closed as no reply for three weeks

**Comment by seanvree** [comment]
FYI:

I think I'm having this issue too. 

Log file is present, and I initialized it.  At the top of the log.json appears:  "'{"log": []}' "

speedtest.sh is just not writing to it.

**Comment by kitsunekyo** [comment]
hm. thats weird, have you checked if speedtest.sh outputs anything? we're trying to pipe it's output into the log file. so if it doesnt output anything, it wont write to the file

**Comment by seanvree** [comment]
@kitsunekyo - yes, it outputs just fine, just doesn't write it to the log.json.
