### ISSUE TITLE
Move hardcoded links to a config file

### ISSUE THREAD

**Issue by tobias-kuendig** [kitsunekyo/internet-speed-log#4]
For example:

https://github.com/kitsunekyo/internet-speed-log/blob/master/js/app.js#L153

**Comment by Phrohdoh** [comment]
Just how should this be used with a local filepath?

I am not exposing my `log.json` to the web currently.

Is that a requirement?

**Comment by tobias-kuendig** [comment]
With the current setup, yes. Its loaded via ajax request.

Taryn Hill <notifications@github.com> schrieb am Sa., 21. Jan. 2017, 03:27:

**Comment by claym** [comment]
Yep, would really appreciate this, so I can git pull without issues :) 👍

**Comment by claym** [comment]
Oh! Might actually be smart to put all the texts into some sort of internationalized file.

Would help as I don't speak German :D

**Comment by kitsunekyo** [comment]
i have now moved pretty much all translatable copy, and configuration values into a config.json file. hope this makes the experience a bit better :)
