### ISSUE TITLE
Nothing shows on Safari (iOS or MacOS)

### ISSUE THREAD

**Issue by ShoGinn** [kitsunekyo/internet-speed-log#7]
So it works on  Firefox and Chrome.. but its just a blank page on Safari.

The page source is correct just nothing is being shown.

I have tried to figure out why but my skills are lacking!

**Comment by kitsunekyo** [comment]
your safari probably doesnt support most of the ES6 javascript i use here. please make sure to use a proper browser for such homebrew stuff. i have no requirement at the moment to make it work in all browsers

**Comment by ShoGinn** [comment]
@kitsunekyo thanks for at least pointing me in the right direction.
